name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: write

jobs:
  build:
    runs-on: [self-hosted] # ラベルは適宜調整してください
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # Dockerイメージにインストール済みのため、このステップは不要
      # - name: Install system dependencies
      #  run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev lsb-release

      # actions/setup-python を使うことで、pipのキャッシュが効くようになります
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 毎回依存関係をインストールする
      - name: Install dependencies
        run: pip install -e .[test,dev]
      - name: Lint with ruff
        run: ruff check .
      - name: Format with ruff
        run: ruff format --check .
      - name: Type check with mypy
        run: mypy . --ignore-missing-imports
      - name: Test with pytest
        run: pytest -m "unit" --cov=. --cov-report=xml
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml